### PR TITLE
Regen for GString support

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by EPashkin** [comment]
@philn Maybe it early to regen all gtk-rs crates:
we have possibly unfinished works on class refactoring.

@sdroege You think that we ready for full regen?

**Comment by sdroege** [comment]
> @sdroege You think that we ready for full regen?

Sure, it all works. I'll have patches for another regen ready some time late next week probably, better to regen things now too.

**Comment by EPashkin** [comment]
@philn Thanks, 👍

**Comment by EPashkin** [comment]
Nighlly 3.4 travis failing by clippy errors, maybe we need add more `allow`.

**Comment by philn** [comment]
Ah, I see `cast_ptr_alignment` errors here. Are you talking about those?

**Comment by EPashkin** [comment]
and `wrong_self_convention` too.
Also maybe need add prefix "clippy:" to all of this to remove warning completely.
Not sure if this really needed now.
@sdroege, @GuillaumeGomez what you think?

**Comment by philn** [comment]
Seems to be a consequence of https://github.com/gtk-rs/gir/pull/673

**Comment by sdroege** [comment]
>  Also maybe need add prefix "clippy:" to all of this to remove warning completely.

If you add that, then 1.31 is the earliest version things will compile with at all :)

**Comment by EPashkin** [comment]
@sdroege Yes, and that is very sad.

**Comment by philn** [comment]
So what's the action point here?

**Comment by sdroege** [comment]
Add the missing `use glib;` :)

**Comment by philn** [comment]
For this PR I think Sebastian is preparing a PR for the gir codegen slippy warnings, so I'll wait :)

**Comment by EPashkin** [comment]
@philn IMHO you just can add 2 ignore for clippy (without prefix).

**Comment by philn** [comment]
Can this one be reviewed now?

**Comment by sdroege** [comment]
Good to go. @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
